name: CI Config
description: Nami CI config action
inputs:
  ref-name:
    description: Name of the branch that triggered the CI workflow
    required: true
outputs:
  environment:
    description: GitHub environment to be used
    value: ${{ steps.eval.outputs.environment }}
  target-env-name:
    description: Name of the target AWS environment
    value: ${{ steps.eval.outputs.target-env-name }}
  image-name:
    description: ECR image tag to be used
    value: ${{ steps.eval.outputs.image-name }}
runs:
  using: composite
  steps:
    - id: eval
      shell: bash
      run: |
        case ${{ inputs.ref-name }} in \
          master  ) echo "environment=prod"       >> $GITHUB_OUTPUT && echo "target-env-name=prod"      >> $GITHUB_OUTPUT && echo "image-name=$SERVICE_NAME"          >> $GITHUB_OUTPUT;; \
          demo    ) echo "environment=dev"        >> $GITHUB_OUTPUT && echo "target-env-name=demo"      >> $GITHUB_OUTPUT && echo "image-name=demo-$SERVICE_NAME"     >> $GITHUB_OUTPUT;; \
          release ) echo "environment=dev"        >> $GITHUB_OUTPUT && echo "target-env-name=release"   >> $GITHUB_OUTPUT && echo "image-name=release-$SERVICE_NAME"  >> $GITHUB_OUTPUT;; \
          *       ) echo "environment=undefined"  >> $GITHUB_OUTPUT && echo "target-env-name=undefined" >> $GITHUB_OUTPUT && echo "image-name=undefined"              >> $GITHUB_OUTPUT;; \
        esac
