name: CI/CD
on: workflow_call
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: Nami-gg/nami-github/get-node-modules@v1
      - name: Test
        run: npm run test
  deploy:
    runs-on: ubuntu-latest    
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: Nami-gg/nami-github/get-node-modules@v1
      - name: Build
        run: npm run build
      #aws creds
      - name: Deploy
        run: npm run deploy